Update libzmq to 4.3.4 to attempt to fix macOS setup error
Hopefully it fixes this error on macOS when installing Jupyter server:

ImportError: dlopen(/Applications/MedicalImaging/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so, 1): Library not loaded: @loader_path/../../.dylibs/libzmq.5.dylib
  Referenced from: /Applications/MedicalImaging/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so
  Reason: Incompatible library version: constants.cpython-36m-darwin.so requires version 8.0.0 or later, but libzmq.5.dylib provides version 5.0.0

https://discourse.slicer.org/t/is-slicerjupyter-broken-on-macos-due-to-argon2-cffi-again/15823/11