Fix 500: server error by updating pygments
pygments>=2.4.1 required for current Jupyter

With current 2.3.1 version we got these errors:

Error during installation:

[INFO][Python] 26.09.2020 11:21:38 [Python] (C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\bin\Python\slicer\util.py:2510) - ERROR: jupyterlab-pygments 0.1.1 has requirement pygments<3,>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
[INFO][Stream] 26.09.2020 11:21:38 [] (unknown:0) - ERROR: jupyterlab-pygments 0.1.1 has requirement pygments<3,>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
[INFO][Python] 26.09.2020 11:21:38 [Python] (C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\bin\Python\slicer\util.py:2510) - ERROR: nbconvert 6.0.6 has requirement pygments>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
[INFO][Stream] 26.09.2020 11:21:38 [] (unknown:0) - ERROR: nbconvert 6.0.6 has requirement pygments>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.

Error when starting notebook:

[E 11:30:07.336 NotebookApp] Uncaught exception GET /notebooks/Untitled5.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/notebooks/Untitled5.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\asyncio\futures.py", line 329, in __iter__
        return self.result()  # May raise too.
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\asyncio\futures.py", line 243, in result
        raise self._exception
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\tornado\gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\notebook\handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\base\handlers.py", line 512, in render_template
        return template.render(**ns)
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\jinja2\environment.py", line 1090, in render
        self.environment.handle_exception()
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\templates\notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\notebook\notebook\handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\nbconvert\__init__.py", line 4, in <module>
        from .exporters import *
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\nbconvert\exporters\html.py", line 19, in <module>
        from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
      File "C:\Users\andra\AppData\Local\NA-MIC\Slicer 4.11.0-2020-09-25\lib\Python\Lib\site-packages\nbconvert\filters\markdown_mistune.py", line 23, in <module>
        from pygments import highlight
    ModuleNotFoundError: No module named 'pygments'
[E 11:30:07.349 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Dest": "document",
      "Referer": "http://localhost:8889/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,hu;q=0.8",
      "Cookie": "_xsrf=2|198eb6da|f1e57ca9375ab5ded139691b0c555d1d|1599615740; username-localhost-8891=\"2|1:0|10:1600967081|23:username-localhost-8891|44:MTQ5MjBlNDBhNzJmNDM3OTk3OTMzYWIxYTFlODI5YzU=|403e0a46364180bdc66a450d4405028e944b49ee6c8821e9df6cd0029c54c5d3\"; username-localhost-8890=\"2|1:0|10:1600968670|23:username-localhost-8890|44:ODA5OTZhZGE5OTRiNDMyMGEzNTA1NTZiZDZlNjMwZTI=|1d19743510c9720a7e54d8b6546408ed2c9290979f4eb6a8472281e9451032cf\"; username-localhost-8888=\"2|1:0|10:1601133946|23:username-localhost-8888|44:ZWE3ZTBjYmE2YmI5NGQ3NGI2NWVjYzQxMDBmMzA2Njk=|bb0ab24815b8ff1d143db563fdccdb4a2066d33e9a15e04c5b34244209ab2873\"; username-localhost-8889=\"2|1:0|10:1601134203|23:username-localhost-8889|44:YzFiZTVmNTlkZTA0NDBkMGIxOGQzYTRkZWU0MTdkZTU=|655d126024685feea6f236753293afc72e90260f085d1f235da5c8a30bc4300f\""
    }
[E 11:30:07.350 NotebookApp] 500 GET /notebooks/Untitled5.ipynb (::1) 105.01ms referer=http://localhost:8889/tree