Roll back to earler xeus-python version to fix runtime error on macOS
Windows and linux build are still broken, but recent updates broke Mac runtime, so until Windows is fixed, roll back to a previously working version on macOS:

    ERROR: during execute_request
    make_tuple(): unable to convert arguments to Python object (compile in debug mode for details)

Details:

Revert "ENH: Update xeus-python, xeus, and jedi libraries to get new features and fixes"
This reverts commit 47226c0bbbb1be2d66804734671caea787dfb0b4.

Revert "Update xeus and nlohmann-json to fix Windows build error"
This reverts commit fb132d045e223ae56dcca1af278804442544da2c.